---
title: "Projects"
---

------------------------------------------------------------------------

## Selected projects over the last 2 years

### Predicting Market Direction for Cocoa Futures

Based on supply and demand data as well as key weather events I built time series models in order to predict the direction of price changes in futures contracts for cocoa in London and New York. I used prophet library and Keras, using recurrent neural networks. This model is used by traders in ECOM on a daily basis.

### Predicting Cocoa Production

In this project I used climatic variables to predict the yield of two crop seasons for cocoa in Côte d'Ivore. The model was a series of ensemble models that weighted the anomalies for each week/month and adjusted the forecast. The predictions have been tested over the last 2 years (4 seasons) with accurate results, even with models with early information.

### Predicting loss of suitability of coffee and cocoa due to climate change

Climate change is having a major impact on the production of cocoa and coffee around the world. I used several models (Random Forest, Neural Networks and XGBoost) to model the current suitability of cocoa and coffee using several climatic variables. Once the model was calibrated on current conditions, the predictions were applied to future conditions to understand either the expansion or contraction of the areas of production that are suitable today. The results of these models has helped to develop the priorities to mitigate dramatic changes in the tropics.

### Amex Default Prediction

I used this data to train junior peers to show them how to use different classification methods to extract value of large datasets. The data came from a Kaggle competition. I used gradient boosting decision trees. Specifically, I trained and evaluated the LGBMClassifier, XGBClassifier and the CatBoostClassifier models with gold standard results in the context of the competition to successfully identify whether a customer would default on their repayments of credit.
