---
title: "Publications"
---

2020: **Beltrán JD** and Puddifoot R: ECOM research into global warming and its effect on suitability for cocoa production. 'AGEFI Commodities, special edition, Disruption in a Disrupted World. April: 22

2017: Yang X, Hu R, Yin H, Jenkins J, Shu S, Tang H, Liu D, Weighill DA, Ha J, Heyduk K, Goodstein DM, Guo H, Moseley RC, Fitzek E, Jawdy S, Zhang Z, Xie M, Hartwell J, Grimwood J, Abraham PE, Mewalal R, Yim WC, **Beltrán JD**, Boxall SF, Dever LV, Palla KJ, Albion R, Garcia T, Mayer J, Lim SD, Wai CM, Van Buren R, De Paoli HC, Borland AM, Guo H, Chen J, Muchero W, Yin Y, Jacobson DA, Tschaplinski TJ, Hettich RL, Ming R , Winter K , Leebens-Mack JH, Smith JAC, Cushman J, Schmutz J, Tuskan GA.: *Kalanchoë* genome reveals convergent evolution of crassulacean acid metabolism. *Nature Communications* **8**: 1899

2015: Yang X, Cushman JC, Borland AM, Edwards EJ, Wullschleger SD, Tuskan GA, Owen NA, Griffiths H, Smith JAC, De Paoli HC, Weston DJ, Cottingham R, Hartwell J, Davis SC, Silvera K, Ming R, Schlauch K, Abraham P, Stewart JR, Guo H, Albion R, Ha J, Lim SD, Wone BWM, Yim WC, Garcia T, Mayer JA, Petereit J, Nair SS, Casey E, Hettich RL, Ceusters J, Ranjan P, Palla KP, Yin H, Reyes-García C, Andrade JL, Freschi L, **Beltrán JD**, Dever LV, Boxall SF,Waller J, Davies J, Bupphada P, Kadu N, Winter K, Sage RF, Aguilar CN, Schmutz J, Jenkins J, Holtum JAM. A roadmap for research on crassulacean acid metabolism (CAM) to enhance sustainable food and bioenergy production in a hotter, drier world. New Phytologist 207:491--504.

2014: Poster presentation, "Evolutionary origins and ecophysiology of CAM photosynthesis in the montane genus *Puya* (Bromeliaceae)", 34 th New Phytologist Symposium "Plant Systems Biology and Ecology of CAM plants", Lake Tahoe, Tahoe City, CA, USA, 15--18 July 2014.

2013: **Beltrán JD**., Lasso E., Madriñán S., Virgo A., Winter K.: Juvenile tank-bromeliads lacking tanks: Do they engage in CAM photosynthesis?, Photosynthetica 51: 55--62.

2012: M.Sc. Thesis: CAM or not CAM: A study on juveniles of *Guzmania lingulata*, *Guzmania monostachia* and *Werauhia sanguinolenta* (Bromeliaceae), Universidad de los Andes.

2010: B.Sc. Thesis: Evolution of xerophyte habit in the tribe Tillandsieae (Bromeliaceae): a phylogenetic approach, Universidad de los Andes.
