---
title: "Work Experience"
---

**Lead Data Scientist \| ECOM Trading \| Nov 2022 - Present**

-   Currently leading the data science team at the Research department in ECOM Trading, one of the world’s largest traders of coffee, cotton and cocoa. I started at ECOM Trading in 2019 as a Senior Data Scientist, I was promoted to the role of Lead Data Scientist in November 2022.

-   My career at ECOM has been marked by pivotal contributions to our core product offerings. These contributions span the realms of data infrastructure and data centralisation as well as the creation, deployment and maintenance of machine learning models, which I describe in further detail below.

-   I've played a significant role in the development and maintenance of advanced trading signal models that leverage Supply & Demand dynamics, weather data, and historical price trends. This unique blend of information allows us to predict market behaviour with high precision, creating a strategic advantage in our trading operations.

-   Recognizing the critical importance of sustainability in today's market, I've been instrumental in developing a new framework for measuring deforestation on global farms. This initiative highlights our commitment to responsible trading and provides invaluable insights into environmental impact.

-   To further streamline our processes and ensure data integrity, I've implemented an automated alert system that identifies potential anomalies in cotton, coffee and cocoa price data. This system proactively sends email alerts when irregularities are detected, allowing us to swiftly mitigate potential risks and maintain market-leading accuracy in our data-driven decisions.

**Senior Data Scientist \| ECOM Trading \| Dec 2019 - Nov 2022**

-   Led the development of a comprehensive suite of data products, encompassing dashboards, automatic reports, and web applications in the research department as a senior data scientist.

-   Developed an array of machine learning models to tackle key industry questions, from predicting the supply and demand of commodities like coffee, cotton, and cocoa to estimating crop yields using satellite imagery.

-   Utilized my predictive models to forecast a range of pivotal factors, including the productivity of West African cocoa farms, the medium-term climate change effects on global plantations, and future price dynamics based on climatic variables.

-   Conceived an innovative web application that fused historical deforestation data with georeferenced farm locations, forming a unique deforestation risk model for global farms.

**Product Developer - Data Science \| Decoded \| Oct 2018 - Nov 2019**

-   Pioneered and executed over 40% of the curriculum for Decoded's flagship offering, the Data Academy, fostering data science integration among blue-chip clients, including Societe General, UBS, Unilever, Nike, and M&S.

-   Crafted comprehensive course material covering fundamental coding in Python and R, advanced statistics, and a wide array of machine learning techniques.

-   Authored specialized R and Python modules for an extensive range of topics such as regression analysis, classification methods, neural networks, Big Data handling, time series analysis, and SQL.

-   Regularly hosted workshops to impart these modules to client employees, both in-person and via webinars, and trained new facilitators to carry the torch forward.

**Research Associate - Data Science \| Institute for Risk and Disaster Reduction, University College London \| Jan 2018 - Oct 2018**

-   Developed a machine learning model capable of real-time prediction of potential mosquito breeding points across four cities in Brazil, employing Python, TensorFlow, and Keras to create recurrent neural networks that geospatially modelled virus and mosquito occurrences.

-   The results of my work were manifested in a user-friendly bokeh web application, which I built and was actively used by health professionals in Brazil.

-   Complimenting this, I also created a mobile application to streamline data collection from health professionals on the ground.


